import mongoose from "mongoose";
import bcrypt from "bcrypt";

const customer = new mongoose.Schema({
    full_name:{
        type: String,
        required: true,
        minlength: 5,
        trim: true
    },
    email: {
        type: String,
        required: true,
        lowercase: true,
        trim: true,
        unique: true
    },
    user_name: {
        type: String,
        required: false, // auto generated by system
        unique: true,
    },
    driving_license_number: {
        type: String,
        minlength: 15,
        maxlength: 15,
        required: true,
        unique: true
    },
    phone_number: {
        type: String,
        minlength: 10,
        maxlength: 10,
        required: true,
        unique: true
    },
    country_code: {
        type: String,
        required: true
    },
    avatar: {
        type: String,
        required: false
    },
    password: { // auto generating the password for regional admin and send it to the regional admin email, so that the regional admin can change the password after first login
        type: String,
        required: false,
        minlength: 6
    },
    refresh_token: {
        type: String
    },
    role: {
        type: String,
        required: true,
        enum: ["super_admin", "staff", "regional_admin", "customer", "customer"]
    },
    isProfileCompleted: {
        type: Boolean,
        default: false
    }

}, {
    timestamps: true
})

//  encrypting the password before saving
customer.pre("save", async function(next){  // normal func is used instead of callback func as callback func does not have access to `this` keyword
    if (!this.isModified("password")) return next() // if the password is not modified, then we don't need to hash it again
    
    const salt = await bcrypt.genSalt(10); // generate a salt
    this.password = await bcrypt.hash(this.password, salt) 
    next()
})

export const Customer = mongoose.model("Customer", customer)
// Customer can directly contact mongoDB as it is made with the help of mongoose