import mongoose from "mongoose";
import bcrypt from "bcrypt";

const regional_admin = new mongoose.Schema({
    full_name:{
        type: String,
        required: true,
        minlength: 5,
        trim: true
    },
    email: {
        type: String,
        required: true,
        lowercase: true,
        trim: true,
        unique: true
    },
    user_name: {
        type: String,
        required: false, // auto generated by system
        unique: true,
    },
    addhar_card_number: {
        type: String,
        minlength: 12,
        maxlength: 12,
        required: true,
        unique: true
    },
    phone_number: {
        type: String,
        minlength: 10,
        maxlength: 10,
        required: true,
        unique: true
    },
    country_code: {
        type: String,
        required: true
    },
    avatar: {
        type: String,
        required: false
    },
    password: { // auto generating the password for regional admin and send it to the regional admin email, so that the regional admin can change the password after first login
        type: String,
        required: false,
        minlength: 6
    },
    refresh_token: {
        type: String
    },
    role: {
        type: String,
        required: true,
        enum: ["super_admin", "staff", "regional_admin", "transporter", "customer"]
    },
    isProfileCompleted: {
        type: Boolean,
        default: false
    }

}, {
    timestamps: true
})

export const RegionalAdmin = mongoose.model("RegionalAdmin", regional_admin)
// RegionalAdmin can directly contact mongoDB as it is made with the help of mongoose