import mongoose from "mongoose";
import bcrypt from "bcrypt";

const regional_admin = new mongoose.Schema({
    full_name:{
        type: String,
        required: true,
        minlength: 5,
        trim: true
    },
    email: {
        type: String,
        required: true,
        lowercase: true,
        trim: true,
        unique: true
    },
    user_name: {
        type: String,
        required: false, // auto generated by system
        unique: true,
    },
    addhar_card_number: {
        type: String,
        length: 12,
        required: true,
        unique: true
    },
    phone_number: {
        type: String,
        length: 10,
        required: true,
        unique: true
    },
    country_code: {
        type: String,
        required: true
    },
    avatar: {
        type: String,
        required: false
    },
    password: { // auto generating the password for regional admin and send it to the regional admin email, so that the regional admin can change the password after first login
        type: String,
        required: false,
        minlength: 6
    },
    refresh_token: {
        type: String
    },
    role: {
        type: String,
        required: true,
        enum: ["super_admin", "regional_admin", "transporter", "customer"]
    },
    isProfileCompleted: {
        type: Boolean,
        default: false
    }

}, {
    timestamps: true
})

//  encrypting the password before saving
regional_admin.pre("save", async function(next){  // normal func is used instead of callback func as callback func does not have access to `this` keyword
    this.password = this.full_name.split(" ")[0] + Math.floor(Math.random() * 1000000) // auto generating the password

    const salt = await bcrypt.genSalt(10); // generate a salt
    this.password = await bcrypt.hash(this.password, salt) 
    next()
})

export const RegionalAdmin = mongoose.model("RegionalAdmin", regional_admin)
// RegionalAdmin can directly contact mongoDB as it is made with the help of mongoose