import mongoose from "mongoose";
import bcrypt from "bcrypt";
import { UserRole } from "../constants.js";
import mongooseAggregatePaginate from "mongoose-aggregate-paginate-v2";

const super_admin = new mongoose.Schema({
    id: {
      type: String,
      unique: true,
      default: function () {
        return this._id.toString();
      },
    },
    full_name:{
        type: String,
        required: true,
        minlength: 2,
        trim: true
    },
    user_name: {
        type: String,
        required: false, // auto generated by system
        unique: true,
        sparse: true,
    },
    email: {
        type: String,
        required: true,
        lowercase: true,
        trim: true,
        unique: true
    },
    phone_number: {
        type: String,
        minlength: 10,
        maxlength: 10,
        required: true,
        unique: true,
        sparse: true
    },
    country_code: {
        type: String,
        required: true
    },
    avatar: {
        type: String,
        required: false, 
        default: "N/A"
    },
    password: {
        type: String,
        required: true,
        minlength: 6
    },
    refresh_token: {
        type: String
    },
    role: {
      type: String,
      required: true,
      default: UserRole.SUPER_ADMIN,
      enum: [UserRole.SUPER_ADMIN],
    },
    isProfileCompleted: {
        type: Boolean,
        default: false
    },
    kyc_status: {
        type: String,
        enum: ["pending", "approved", "rejected"],
        default: "pending"
    }

}, {
    timestamps: true
})

//  encrypting the password before saving
super_admin.pre("save", async function(next){  // normal func is used instead of callback func as callback func does not have access to `this` keyword
    if (!this.isModified("password")) return next() // if the password is not modified, then we don't need to hash it again

    const salt = await bcrypt.genSalt(10); // generate a salt
    this.password = await bcrypt.hash(this.password, salt) 
    next()
})

super_admin.plugin(mongooseAggregatePaginate) // enabling aggregation pipeline
export const Company = mongoose.model("Company", super_admin)
// Company can directly contact mongoDB as it is made with the help of mongoose