import mongoose from "mongoose";
import bcrypt from "bcrypt";
import { CustomerProfileSchema } from "../models/schemas/profileSchemas.js";
import { UserRole, UserStatus, Gender } from "../constants.js";
import mongooseAggregatePaginate from "mongoose-aggregate-paginate-v2";

const customer = new mongoose.Schema(
  {
    // Core User Fields
    id: {
      type: String,
      unique: true,
      default: function () {
        return this._id.toString();
      },
    },
    full_name: {
      type: String,
      required: true,
      minlength: 2,
      trim: true,
    },
    email: {
      type: String,
      required: true,
      lowercase: true,
      trim: true,
      unique: true,
    },
    phone_number: {
      type: String,
      minlength: 10,
      maxlength: 15,
      required: true,
      unique: true,
      sparse: true,
    },
    country_code: {
      type: String,
      required: true,
      minlength: 3,
      maxlength: 3,
    },
    user_name: {
      type: String,
      required: false, // auto generated by system
      unique: true,
      sparse: true,
    },
    password: {
      type: String,
      required: false,
      minlength: 6,
    },
    refresh_token: {
      type: String,
    },
    role: {
      type: String,
      required: true,
      default: UserRole.CUSTOMER,
      enum: [UserRole.CUSTOMER],
    },
    status: {
      type: String,
      default: UserStatus.PENDING,
      enum: Object.values(UserStatus),
    },
    driving_license_number: {
      type: String,
      minlength: 15,
      maxlength: 15,
      unique: true,
      sparse: true,
    },
    avatar: {
      type: String,
      required: false,
      default: "N/A",
    },
    bio: {
      type: String,
      required: false,
    },
    gender: {
      type: String,
      enum: [null, ...Object.values(Gender)],
      default: null,
    },
    dateOfBirth: Date,
    isVerified: {
      type: Boolean,
      default: false,
    },
    isApproved: {
      type: Boolean,
      default: false,
    },
    lastLoginAt: Date,

    // Customer Profile
    customerProfile: CustomerProfileSchema,
  },
  {
    timestamps: true,
  }
);

// Encrypting the password before saving
customer.pre("save", async function (next) {
  if (!this.isModified("password")) return next();

  const salt = await bcrypt.genSalt(10);
  this.password = await bcrypt.hash(this.password, salt);
  next();
});

customer.plugin(mongooseAggregatePaginate) // enabling aggregation pipeline
export const Customer = mongoose.model("Customer", customer);
// Customer can directly contact mongoDB as it is made with the help of mongoose