import mongoose from "mongoose";
import { UserRole } from "../constants.js";
import mongooseAggregatePaginate from "mongoose-aggregate-paginate-v2";

const staff = new mongoose.Schema({
    id: {
      type: String,
      unique: true,
      default: function () {
        return this._id.toString();
      },
    },
    full_name:{
        type: String,
        required: true,
        minlength: 5,
        trim: true
    },
    station_id: {
        type: mongoose.Schema.Types.ObjectId,
        ref: "Station",
        required: true
     },
    company_id: {
        type: mongoose.Schema.Types.ObjectId,
        ref: "Company",
        required: true
    },
    regional_admin_id: {
        type: mongoose.Schema.Types.ObjectId,
        ref: "RegionalAdmin",
        required: true
    },
    email: {
        type: String,
        required: true,
        lowercase: true,
        trim: true,
        unique: true
    },
    user_name: {
        type: String,
        required: false, // auto generated by system
        unique: true,
        sparse: true,
    },
    addhar_card_number: {
        type: String,
        minlength: 12,
        maxlength: 12,
        required: true,
        unique: true,
        sparse: true
    },
    phone_number: {
        type: String,
        minlength: 10,
        maxlength: 10,
        required: true,
        unique: true,
        sparse: true
    },
    country_code: {
        type: String,
        required: true
    },
    avatar: {
        type: String,
        required: false,
        default: "N/A",
    },
    password: { // auto generating the password for regional admin and send it to the regional admin email, so that the regional admin can change the password after first login
        type: String,
        required: false,
        minlength: 6
    },
    refresh_token: {
        type: String
    },
    role: {
      type: String,
      required: true,
      default: UserRole.STAFF,
      enum: [UserRole.STAFF],
    },
    isProfileCompleted: {
        type: Boolean,
        default: false
    }

}, {
    timestamps: true,
    toJSON: { virtuals: true },
    toObject: { virtuals: true }
})

// Forward relations for bidirectional access via populate.
staff.virtual("station", {
    ref: "Station",
    localField: "station_id",
    foreignField: "_id",
    justOne: true
});

staff.virtual("company", {
    ref: "Company",
    localField: "company_id",
    foreignField: "_id",
    justOne: true
});

staff.virtual("regionalAdmin", {
    ref: "RegionalAdmin",
    localField: "regional_admin_id",
    foreignField: "_id",
    justOne: true
});


staff.plugin(mongooseAggregatePaginate) // enabling aggregation pipeline
export const Staff = mongoose.model("Staff", staff)
// Staff can directly contact mongoDB as it is made with the help of mongoose